### ISSUE TITLE
你好，有roadmap吗？想参与开发？

### ISSUE THREAD

**Issue by liushuchun** [absolute8511/nsq#15]

**Comment by absolute8511** [comment]
目前还有以下功能有待完善:

- etcd的v3接口改造
- 优化顺序一致性消费客户端链接
- 大量延时消息设计优化
- 更多的测试用例
- 更多的开源系统connector
- tag过滤

其他的有新的想法也欢迎讨论 :)

**Comment by liushuchun** [comment]
好的，谢谢，NSQ重度用户，听了你们的讲座，感觉解决了很多痛点。很赞的想法，清晰的逻辑，希望参与进来，先学习一下代码哈。

**Comment by absolute8511** [comment]
好的, 欢迎

**Comment by absolute8511** [comment]
This issue was moved to youzan/nsq#3
