### ISSUE TITLE
More technical documents for the new redesigned NSQ

### ISSUE THREAD

**Issue by absolute8511** [absolute8511/nsq#18]
To make all the technical details clear for the other developers, we need add more documents. So we can have more contributors and it is also helpful to merge it back into mainline.

**Comment by absolute8511** [comment]
Some thoughts on what to write:

- What is the etcd for? @DoraALin
- How the Replication and HA work?  
- How the balance and migrate work?
- About the smart client (r/w, HA, ordered, retry details)   @DoraALin 
- How to use partitions to solve the scalability?
- The difference on the write flow between the old and new
- The difference on the consume between the old and new
- Make deliver in ordered possible
- Defer and Requeue redesign.

Help is appreciate, If anyone want to help, pls reply here and tell which topic you want to contribute.

**Comment by DoraALin** [comment]
take title "What is the etcd for?"

**Comment by absolute8511** [comment]
This issue was moved to youzan/nsq#2
