### ISSUE TITLE
有没有安装文档？

### ISSUE THREAD

**Issue by liushuchun** [absolute8511/nsq#19]
hi,我们想试用看看你们的这个NSQ版本，想问一下有没有详细一些的安装文档？

**Comment by liushuchun** [comment]
@absolute8511 thanks.

**Comment by absolute8511** [comment]
你可以去release页面下载最新的二进制文件, 参考配置文件里面的说明启动即可, 大部分参数和原版差不多, 新增的参数也有说明的

**Comment by liushuchun** [comment]
@absolute8511 好的，多谢，就是多了一个etcd是吧？

**Comment by absolute8511** [comment]
@liushuchun  是的, 多了一个依赖etcd

**Comment by liushuchun** [comment]
@absolute8511 想问一下nsqlookupd服务至少是装3个？我装了2个，
I0502 08:42:45.399683   21319 http.go:1011] nsqadmin.(*httpServer).clusterStatsHandler WARNING: failed to find lookupd leader at this moment

**Comment by feixiao** [comment]
@liushuchun 选举leader应该最少三个，raft算法有规定吧

**Comment by liushuchun** [comment]
@feixiao thanks，好像说是奇数个，我理解错了，我以为是nsqd是要选主的.

**Comment by liushuchun** [comment]
thanks，好像raft说是奇数个，我理解错了，我以为是nsqd是要选主的.

**Comment by absolute8511** [comment]
@liushuchun 你启动nsqd之前, 需要先启动nsqlookupd, 然后配置文件里面的cluster_id, cluster_leadership_addresses要保持一样的. 另外nsqlookupd可以启动2个, 选举是通过etcd的分布式锁接口. lookupd本身不需要raft. 看你的log是nsqadmin的配置不对吧, nsqadmin一般和nsqlookupd同机部署, 然后设置配置文件里面的nsqlookupd_http_addresses即可.

**Comment by liushuchun** [comment]
@absolute8511 好的，多谢多谢，清晰了很多。

**Comment by liushuchun** [comment]
@absolute8511 hi,nsqd 报错，E0503 17:14:04.595317    8165 nsqd_node_etcd.go:238] consistence.(*NsqdEtcdMgr).WatchLookupdLeader get error: 100: Key not found (/NSQMetaData) [8]

**Comment by liushuchun** [comment]
@absolute8511 大神，想问一下,Cluster Status  Not Stable是那块的问题？

**Comment by absolute8511** [comment]
初始化, 新创建topic或者重启节点的时候会显示这个, 过一会集群稳定就ok了

**Comment by liushuchun** [comment]
@absolute8511 好的，多谢多谢。

**Comment by liushuchun** [comment]
![image](https://cloud.githubusercontent.com/assets/4532590/25690244/d74d9196-30c1-11e7-8809-d1909a15ee26.png)

创建topic一直不成功,nsqlookup这边提示：
E0504 12:01:15.632298    3174 http.go:503] nsqlookupd.(*httpServer).doCreateTopic DB: adding topic(dsfdf) failed: ErrType:9 ErrCode:1 : No node is available for topic

**Comment by absolute8511** [comment]
节点不够啊, 你只有一个节点, 创建的 分区数和副本数都只能是1

**Comment by liushuchun** [comment]
抱歉，我没有放全。
![image](https://cloud.githubusercontent.com/assets/4532590/25690755/e4d81624-30c6-11e7-8f6c-59c2c52d5c41.png)
有三个节点的.

**Comment by absolute8511** [comment]
参考这个 https://github.com/absolute8511/nsq/blob/master/doc/NSQ%20reference.md, 3个节点可以创建3分区一副本, 或者1分区3副本的topic, 如果是顺序消费的, 可以建多个分区3副本

**Comment by liushuchun** [comment]
好的，多谢absolute.

**Comment by liushuchun** [comment]
@absolute8511 hi,Vincent.实在是找不到那里配置有误，也没有报错，您得空帮忙看一下,某nsqd的配置：
./nsqd -tcp-address=10.200.20.57:4150 -http-address=10.200.20.57:4151 -https-address=10.200.20.57:4152 -lookupd-tcp-address=10.200.20.59:4160 -lookupd-tcp-address=10.200.20.60:4160 -lookupd-tcp-address=10.200.20.61:4160 -mem-queue-size=1000000 -cluster-id=testperformance -cluster-leadership-addresses=10.200.20.57:2379,10.200.20.58:2379,10.200.20.59:2379  -broadcast-address=10.200.20.57 -rpc-port=4250 -logtostderr -data-path=/disk1/nsq

**Comment by liushuchun** [comment]
某nsqlookupd的配置
./nsqlookupd -logtostderr -tcp-address=10.200.20.60:4160 -http-address=10.200.20.60:4161 -broadcast-address=10.200.20.60 -cluster-id=testperformance -cluster-leadership-addresses=10.200.20.57:2379,10.200.20.58:2379,10.200.20.59:2379 -rpc-port=4250

多谢.

**Comment by absolute8511** [comment]
你把contrib下面的几个配置文件拷贝出来, 修改如下几个配置:

```
broadcast_interface = 监听的网卡名称
cluster_id=
cluster_leadership_addresses=
log_dir=
data_path=
```

然后使用 `nsqd/nsqlookupd -config=/path/to/config` 启动试试

另外, 你创建topic的参数是哪些

**Comment by liushuchun** [comment]
好的，这么有耐心的回复。感谢.
