### ISSUE TITLE
expandable view in topic page in nsqadmin

### ISSUE THREAD

**Issue by DoraALin** [absolute8511/nsq#21]
<img width="468" alt="default" src="https://cloud.githubusercontent.com/assets/6905536/25687503/66486d94-30a9-11e7-8173-12da5d70e417.png">
tables like coordinator status and message distribution could be expandable.

**Comment by absolute8511** [comment]
And also the topic producer connections can be hidden by default.

**Comment by DoraALin** [comment]
duplicated with #26 . Closed.
