### ISSUE TITLE
hide coordinator info in nsqadmin topic page

### ISSUE THREAD

**Issue by DoraALin** [absolute8511/nsq#26]
coordinator info in topic could hide as initial state.
<img width="362" alt="default" src="https://cloud.githubusercontent.com/assets/6905536/26185713/3186d55c-3bbf-11e7-9fc2-3d39c813b0ac.png">

**Comment by DoraALin** [comment]
pr requested in https://github.com/absolute8511/nsq/pull/27

**Comment by absolute8511** [comment]
Maybe also make the pub connections hidden by default

**Comment by DoraALin** [comment]
@absolute8511 Done in #27
